version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:9.6.24-bullseye
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: FRGstgdhr5ywsrg
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
    postgres: